version: "3.9"
services:
  db:
    image: postgres:alpine
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - web
  app:
    image: app
    environment:
      APP_PORT: 9000
      APP_HOST: 127.0.0.1
      APP_DB_URL: postgres://user:pass@localhost:5432/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: shared
